name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'
    - '!*-r[0-9]*'

env:
  BASE_IMAGE_REVISION: 4.71.5

jobs:
  xhprof-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        version: '2.3.10'
        tags: 2.3,2,latest
        platform: linux/amd64,linux/arm64

  image-revision-aliases:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/r')
    needs: [ xhprof-2 ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: image-revision-aliases-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: wodby/images/.github/actions/image-revision-aliases@1c1a2951d6ce2e080e6ab6f62a935f4e34089feb
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
